@file:Suppress("SpellCheckingInspection")

import org.gradle.api.JavaVersion

internal object Versions {
    const val AMAZON_QLDB_DRIVER = "2.0.0"
    const val ASSERTJ = "3.20.2"
    const val AUTH0 = "1.22.0"
    const val AWSSDK = "2.17.9"
    const val AWS_JAVA_SDK = "1.12.37"
    const val AWS_LAMBDA_CORE = "1.2.1"
    const val AWS_LAMBDA_EVENTS = "2.2.2"
    const val AWS_LAMBDA_LOG4J2 = "1.2.0"
    const val BEN_MANES = "0.39.0"
    const val BINTRAY = "1.8.4"
    const val COMMONS_CSV = "1.7"
    const val COMMONS_NET = "3.6"
    const val DAGGER = "2.19"
    const val DETEKT = "1.0.0-RC12"
    const val DOKKA = "0.9.18"
    const val GRADLE = "7.2"
    const val GRAPHIQL_SPRING_BOOT_STARTER = "5.0.2"
    const val GRAPHQL_JAVA = "16.2"
    const val GRAPHQL_JAVA_SPRING_BOOT_STARTER_WEBFLUX = "1.0"
    const val GRAPHQL_JAVA_TOOLS = "5.2.4"
    const val GRAPHQL_SPRING_BOOT_STARTER = "5.0.2"
    const val GSON = "2.8.6"
    const val GUICE = "4.2.2"
    const val HTTPCORE = "4.4.10"
    const val JACKSON = "2.12.4"
    val JAVA = JavaVersion.VERSION_11
    const val JAVAFX = "11.0.1"
    const val JAVAX_INJECT = "1"
    const val JAXB = "2.3.1"
    const val JMOCKIT = "1.43"
    const val JSCH = "0.1.55"
    const val JUNIT = "4.12"
    const val JUNIT5 = "5.7.2"
    const val KODEIN_DI_GENEREIC_JVM = "6.0.1"
    const val KOIN = "1.0.2"
    const val KOTLIN = "1.5.21"
    const val KOTLINX = "1.3.4"
    const val LOG4J = "2.14.1"
    const val LOG4J_KOTLIN = "1.0.0"
    const val LOMBOK = "1.18.4"
    const val MOCKITO = "3.0.0"
    const val MOCKK = "1.12.0"
    const val MOCK_FTP_SERVER = "2.7.1"
    const val NEBULA_PUBLISH = "9.4.5"
    const val NEBULA_RELEASE = "9.2.0"
    const val OK_HTTP = "4.2.2"
    const val ORG_ECLIPSE_JDT_ANNOTATION = "2.2.100"
    const val PICOCLI = "4.2.0"
    const val RXJAVA = "2.2.4"
    const val SHADOW_JAR = "7.0.0"
    const val SHIPKIT = "2.3.1"
    const val SLF4J_API = "1.7.25"
    const val SPRING = "5.3.9"
    const val SPRING_BOOT = "2.2.6.RELEASE"
    const val SPRING_DEPENDENCY_MANAGEMENT = "1.0.6.RELEASE"
    const val STRIPE_JAVA = "20.14.0"
    const val TRUTH = "0.42"
    const val VALIDATION_API = "2.0.1.Final"
}
